name: aspo_production
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_prod_container
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - aspo_api
      - aspo_web
  aspo_api:
    build:
      context: ./aspo_api
      dockerfile: Dockerfile
    container_name: aspo_prod_api_container
    mem_limit: 128m
    hostname: aspo_api
    environment:
      - PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_TOKEN_SECRET_KEY=${JWT_REFRESH_TOKEN_SECRET_KEY}
  aspo_web:
    build:
      context: ./aspo_web
      dockerfile: Dockerfile
    container_name: aspo_prod_web_container
    mem_limit: 128m
    hostname: aspo_web
    environment:
      - VITE_PORT=${WEB_PORT}
