name: aspo
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx_container
    depends_on:
      - aspo_api
      - aspo_web
    ports:
      - "3050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  aspo_api:
    build:
      context: ./aspo_api
      dockerfile: Dockerfile.dev
    container_name: aspo_api_container
    volumes:
      - /aspo_api/node_modules
      - ./aspo_api:/aspo_api
    environment:
      - PORT=${API_PORT}
  aspo_web:
    build:
      context: ./aspo_web
      dockerfile: Dockerfile.dev
    volumes:
      - /aspo_web/node_modules
      - ./aspo_web:/aspo_web
    environment:
      - VITE_PORT=${WEB_PORT}
