name: aspo_development
services:
  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   container_name: nginx_dev_container
  #   depends_on:
  #     - aspo_api
  #     - aspo_web
  #   ports:
  #     - "3050:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./aspo_web:/var/www/aspo_web
  #     - ./aspo_api:/var/www/aspo_api
  #   environment:
  #     - NGINX_HOST=nginx_dev_container
  #     - NGINX_PORT=3050
  #   command: >
  #     sh -c "nginx -g 'daemon off;' &
  #        inotifywait -m -r -e modify,create,delete --format '%w%f' /var/www/aspo_web /var/www/aspo_api |
  #        while read file; do
  #          echo 'File changed: $file';
  #          nginx -s reload;
  #        done"
  aspo_api:
    build:
      context: ./aspo_api
      dockerfile: Dockerfile.dev
    container_name: aspo_dev_api_container
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - /aspo_api/node_modules
      - ./aspo_api:/aspo_api
    environment:
      - PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_TOKEN_SECRET_KEY=${JWT_REFRESH_TOKEN_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
  aspo_web:
    build:
      context: ./aspo_web
      dockerfile: Dockerfile.dev
    container_name: aspo_dev_web_container
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - /aspo_web/node_modules
      - ./aspo_web:/aspo_web
    environment:
      - VITE_PORT=${WEB_PORT}
